### ISSUE TITLE
 Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [RyanLeeLY/Coolog#1]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by RyanLeeLY** [comment]
No, certainly not. Actually, I am planning to do this.

**Comment by anharismail** [comment]
Okay Sir, No problem.

**Comment by RyanLeeLY** [comment]
Thank you!
