### ISSUE TITLE
dateStringWithTimeInterval 计算的时间和实际时间相差一个小时

### ISSUE THREAD

**Issue by jaoye** [RyanLeeLY/Coolog#2]
dateStringWithTimeInterval 计算的时间和实际时间相差一个小时

**Comment by RyanLeeLY** [comment]
0.3.1修复了这个错误。出于性能考虑，这里使用了c的标准库time.h，现在在log中添加了isdst的值来区分是否是夏令时。当isdst=1时，北京时间会比log中的时间早1个小时。
