### ISSUE TITLE
Demo在真机上运行时，浏览器上websocket不能正确连接到app, 模拟机上可以

### ISSUE THREAD

**Issue by chiyun1** [RyanLeeLY/Coolog#3]
RT, 没有修改代码，模拟机上运行没有问题，在真机上连接不上。App中都没有 进入到accept。浏览器输出是非常喜欢的一个功能，希望能够解决。
设备：iPhoneX
系统：ios12.1.2

**Comment by RyanLeeLY** [comment]
在0.3.2的版本中加上的error的log，你更新后看一下有没有相关log，可以发给我。
