### ISSUE TITLE
Undefined symbols for architecture arm64:_OBJC_CLASS_$_COLLogManager", referenced from...

### ISSUE THREAD

**Issue by zhang-can-lin** [RyanLeeLY/Coolog#4]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_COLLogManager", referenced from:
      objc-class-ref in libXXX.a(XXXX.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

作者您好，感谢您的开源精神， 我把文件日志相关的源码嵌入到我的程序，出现了这种链接错误，我没有很好地解决办法，希望能得到您的帮助

**Comment by RyanLeeLY** [comment]
是手动导入还是cocoapods导入的？

**Comment by zhang-can-lin** [comment]
手动导入的，因为需要这个文件日志， 按照项目的Architecture， 在最下面一层只导入了NSLog和FileLog

**Comment by RyanLeeLY** [comment]
检查一下COLLogManager这个类有没有添加到compile sources，如还有问题麻烦发一下工程的目录。
